[project]
name = "steam-update-inhibit-sleep"
version = "0.1.0"
description = "Leave Steam installing stuff without system going to sleep until it's finished"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbus-python>=1.4.0",
    "inotify-simple>=1.3.5",
]
